name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0

      - name: Install packages
        run: npm i
      
      - name: Build project
        run: |
          npm run build,
          echo 'lassemoldrup.dk' > CNAME.
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          repository-name: lassemoldrup/lassemoldrup.github.io
          branch: master
          folder: public
          token: ${{ secrets.PAT }}
          single-comit: true
          dry-run: true
